### ISSUE TITLE
Rss feed?

### ISSUE THREAD

**Issue by ghost** [reymon359/gatsby-personal-site#751]
Hey I was browsing your site while looking for articles about coliving. Really enjoyed yours. I was wondering if you could add a rss feed for the blog?

Something like https://ramonmorcillo.com/blog/feed.xml and adding [RSS feed autodiscovery](https://dri.es/rss-auto-discovery) to the page head tag

**Comment by reymon359** [comment]
Hey @sethidden thanks for the feedback. 

I will take a look at it before writing the next one :)

**Comment by reymon359** [comment]
> This will suffice for me for now (rsshub can generate rss feeds for gh issue lists on a repo, and since you add an issue for each article with a link to it, it's good enough fro me https://rsshub.app/github/issue/reymon359/gatsby-personal-site/all

Happy you found a way, I didn't know about that. Thanks for sharing!
